name: Deploy Spring Boot to GCP VM

on:
  push:
    branches:
      - main  # Deploy only when code is pushed to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: fleet-tracker-jar
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: fleet-tracker-jar
          path: .

      - name: Copy JAR to GCP VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          source: "*.jar"
          target: "~/fleet-tracker/"

      - name: Restart Application on GCP VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            cd ~/fleet-tracker/
            pkill -f 'java -jar' || true  # Stop running app
            nohup java -jar *.jar > app.log 2>&1 &
