name: CI/CD Pipeline for fleet-tracker

on:
  push:
    branches:
      - main  # Change to your production branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to Server
        run: |
          ssh -T -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd Fleet-Tracker
            git pull origin main
            cd server
            docker build -t fleet-tracker . 
            docker stop fleet-tracker-container || true
            docker rm fleet-tracker-container || true
            docker run -p 8080:8080 --name fleet-tracker-container fleet-tracker
          EOF